import {useEffect,useRef,useState} from 'react';
import {useAuth} from '../contexts/AuthContext';
import {supabase} from '../lib/supabase';

type Person={id:string;full_name:string;username:string};
type Message={id:string;sender_id:string;content:string;created_at:string};
export default function MessagesPage(){
 const{session}=useAuth();const[people,setPeople]=useState<Person[]>([]);const[selected,setSelected]=useState<Person|null>(null);const[conversationId,setConversationId]=useState('');const[messages,setMessages]=useState<Message[]>([]);const[draft,setDraft]=useState('');const[status,setStatus]=useState('');const[loading,setLoading]=useState(true);const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!supabase||!session){setLoading(false);return}supabase.from('connections').select('requester_id,recipient_id,requester:profiles!connections_requester_id_fkey(id,full_name,username),recipient:profiles!connections_recipient_id_fkey(id,full_name,username)').eq('status','accepted').or(`requester_id.eq.${session.user.id},recipient_id.eq.${session.user.id}`).then(({data,error})=>{setLoading(false);if(error)setStatus('Unable to load connections.');else setPeople((data??[]).map((r:any)=>r.requester_id===session.user.id?r.recipient:r.requester).filter(Boolean))})},[session]);
 useEffect(()=>{if(!conversationId||!supabase)return;supabase.from('messages').select('id,sender_id,content,created_at').eq('conversation_id',conversationId).order('created_at').then(({data,error})=>{if(error)setStatus('Unable to load messages.');else setMessages(data??[])});const channel=supabase.channel(`messages:${conversationId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${conversationId}`},payload=>setMessages(current=>current.some(m=>m.id===payload.new.id)?current:[...current,payload.new as Message])).subscribe();return()=>{void supabase.removeChannel(channel)}},[conversationId]);useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[messages]);
 async function open(person:Person){if(!supabase)return;setStatus('Opening conversation…');const{data,error}=await supabase.rpc('start_private_conversation',{other_user_id:person.id});if(error){setStatus('Messaging is unavailable for this connection.');return}setSelected(person);setConversationId(data);setMessages([]);setStatus('')}
 async function send(e:React.FormEvent){e.preventDefault();const content=draft.trim();if(!supabase||!session||!conversationId||!content)return;setDraft('');const{error}=await supabase.from('messages').insert({conversation_id:conversationId,sender_id:session.user.id,content});if(error){setDraft(content);setStatus('Message could not be sent. Please try again.')}}
 return <section className="page"><div className="eyebrow">Private messaging</div><h1>Messages</h1><p>Message accepted connections. Conversations are private to their members.</p>{status&&<p className="form-status" role="status">{status}</p>}<div className="message-layout"><aside className="conversation-list"><h2>Accepted connections</h2>{loading&&<p className="muted">Loading connections…</p>}{people.map(p=><button className={`person-button ${selected?.id===p.id?'selected':''}`} key={p.id} onClick={()=>open(p)}>{p.full_name}<small>@{p.username}</small></button>)}{!loading&&!people.length&&<p className="muted">Accept a connection to start messaging.</p>}</aside><div className="chat-panel">{selected?<><header><strong>{selected.full_name}</strong><span>@{selected.username}</span></header><div className="chat-messages">{messages.map(m=><div className={`bubble ${m.sender_id===session?.user.id?'mine':''}`} key={m.id}>{m.content}</div>)}<div ref={bottom}/></div><form className="message-compose" onSubmit={send}><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} maxLength={5000} placeholder="Write a message…" required rows={2}/><button className="primary">Send</button></form></>:<div className="empty-state"><h2>Select a connection</h2><p>Choose an accepted connection to open a private conversation.</p></div>}</div></div></section>}
