import React from 'react';
import {BrowserRouter,Link,Route,Routes} from 'react-router-dom';
import {AuthProvider} from './contexts/AuthContext';
import Layout from './components/Layout';
import ProtectedRoute from './components/ProtectedRoute';
import {supabase} from './lib/supabase';

function Home(){return <section className="hero"><div className="brand"><span className="mark">✦</span> ADUSTECH <b>Connect</b></div><div className="eyebrow">Student-first · Respectful · Private by design</div><h1>Meet. Connect.<br/><span>Match. Belong.</span></h1><p>Discover friends, study partners, communities and meaningful connections across ADUSTECH.</p><div className="actions"><Link className="primary" to="/signup">Start connecting</Link><Link className="secondary" to="/discover">Explore students</Link></div><small>ADUSTECH Connect is an independent student platform and is not affiliated with or officially endorsed by ADUSTECH unless otherwise stated.</small></section>}
function Auth({signup=false}:{signup?:boolean}){async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const email=String(f.get('email')),password=String(f.get('password'));const result=signup?await supabase.auth.signUp({email,password,options:{data:{full_name:String(f.get('name')||'')}}}):await supabase.auth.signInWithPassword({email,password});if(result.error)alert(result.error.message)}return <main className="auth"><form onSubmit={submit}><Link to="/" className="brand"><span className="mark">✦</span> ADUSTECH <b>Connect</b></Link><h1>{signup?'Create your account':'Welcome back'}</h1>{signup&&<input name="name" placeholder="Full name" required/>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password (8+ characters)" minLength={8} required/><button className="primary">{signup?'Sign up':'Log in'}</button><Link to={signup?'/login':'/signup'}>{signup?'Already registered? Log in':'New here? Create an account'}</Link></form></main>}
function Page({title}:{title:string}){return <section className="page"><div className="eyebrow">ADUSTECH Connect</div><h1>{title}</h1><p>No data to show yet. Complete your profile or check back later.</p></section>}
function Protected({children}:{children:React.ReactNode}){return <ProtectedRoute><Layout>{children}</Layout></ProtectedRoute>}
export default function App(){return <AuthProvider><BrowserRouter><Routes><Route path="/" element={<Layout><Home/></Layout>}/><Route path="/login" element={<Auth/>}/><Route path="/signup" element={<Auth signup/>}/><Route path="/discover" element={<Protected><Page title="Discover students"/></Protected>}/><Route path="/matches" element={<Protected><Page title="Matches"/></Protected>}/><Route path="/messages" element={<Protected><Page title="Messages"/></Protected>}/><Route path="/communities" element={<Protected><Page title="Communities"/></Protected>}/><Route path="/profile" element={<Protected><Page title="Your profile"/></Protected>}/><Route path="/settings" element={<Protected><Page title="Settings"/></Protected>}/><Route path="*" element={<Page title="Page not found"/>}/></Routes></BrowserRouter></AuthProvider>}
