import React,{useState} from 'react';
import {BrowserRouter,Link,Route,Routes,useNavigate} from 'react-router-dom';
import {AuthProvider} from './contexts/AuthContext';
import Layout from './components/Layout';
import ProtectedRoute from './components/ProtectedRoute';
import ProfilePage from './pages/ProfilePage';
import PublicProfilePage from './pages/PublicProfilePage';
import DiscoverPage from './pages/DiscoverPage';
import ConnectionsPage from './pages/ConnectionsPage';
import MessagesPage from './pages/MessagesPage';
import CommunitiesPage from './pages/CommunitiesPage';
import SettingsPage from './pages/SettingsPage';
import NotificationsPage from './pages/NotificationsPage';
import {supabase} from './lib/supabase';
function Home(){return <section className="hero"><div className="brand"><span className="mark">✦</span> ADUSTECH <b>Connect</b></div><div className="eyebrow">Student-first · Respectful · Private by design</div><h1>Meet. Connect.<br/><span>Match. Belong.</span></h1><p>Discover friends, study partners, communities and meaningful connections across ADUSTECH.</p><div className="actions"><Link className="primary" to="/signup">Start connecting</Link><Link className="secondary" to="/discover">Explore students</Link></div><small>ADUSTECH Connect is an independent student platform and is not affiliated with or officially endorsed by ADUSTECH unless otherwise stated.</small></section>}
function Auth({signup=false}:{signup?:boolean}){const[status,setStatus]=useState('');const[busy,setBusy]=useState(false);const navigate=useNavigate();async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus('');if(!supabase){setStatus('Supabase is not configured.');return}const f=new FormData(e.currentTarget);const email=String(f.get('email')||'').trim();const password=String(f.get('password')||'');setBusy(true);if(signup){const result=await supabase.auth.signUp({email,password,options:{data:{full_name:String(f.get('name')||'').trim()}}});if(result.error){setBusy(false);setStatus(result.error.message);return}if(!result.data.session){const login=await supabase.auth.signInWithPassword({email,password});if(login.error){setBusy(false);setStatus('Signup succeeded, but automatic login failed. In Supabase, turn off Authentication → Providers → Email → Confirm email, then try again.');return}}setBusy(false);navigate('/profile');return}const result=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error){setStatus(result.error.message);return}navigate('/profile')}return <main className="auth"><form onSubmit={submit}><Link to="/" className="brand"><span className="mark">✦</span> ADUSTECH <b>Connect</b></Link><h1>{signup?'Create your account':'Welcome back'}</h1>{signup&&<input name="name" placeholder="Full name" required/>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password (8+ characters)" minLength={8} required/><button className="primary" disabled={busy}>{busy?'Please wait…':signup?'Sign up':'Log in'}</button>{status&&<p className="form-status" role="alert">{status}</p>}{!signup&&<Link to="/forgot-password">Forgot password?</Link>}<Link to={signup?'/login':'/signup'}>{signup?'Already registered? Log in':'New here? Create an account'}</Link></form></main>}
function ForgotPassword(){const[status,setStatus]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase){setStatus('Supabase is not configured.');return}const{error}=await supabase.auth.resetPasswordForEmail(String(new FormData(e.currentTarget).get('email')||''),{redirectTo:`${window.location.origin}/reset-password`});setStatus(error?error.message:'If an account exists for that email, a reset link has been sent.')}return <main className="auth"><form onSubmit={submit}><h1>Reset password</h1><input name="email" type="email" placeholder="Email" required/><button className="primary">Send reset link</button>{status&&<p className="form-status" role="status">{status}</p>}<Link to="/login">Back to login</Link></form></main>}
function ResetPassword(){const[status,setStatus]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase){setStatus('Supabase is not configured.');return}const f=new FormData(e.currentTarget);const password=String(f.get('password')||'');if(password!==String(f.get('confirm')||'')){setStatus('Passwords do not match.');return}const{error}=await supabase.auth.updateUser({password});setStatus(error?error.message:'Password updated. You can now log in.')}return <main className="auth"><form onSubmit={submit}><h1>Choose a new password</h1><input name="password" type="password" minLength={8} placeholder="New password" required/><input name="confirm" type="password" minLength={8} placeholder="Confirm password" required/><button className="primary">Update password</button>{status&&<p className="form-status" role="status">{status}</p>}<Link to="/login">Go to login</Link></form></main>}
function Page({title}:{title:string}){return <section className="page"><h1>{title}</h1><p>This page does not exist.</p><Link className="secondary" to="/">Return home</Link></section>}
function Protected({children}:{children:React.ReactNode}){return <ProtectedRoute><Layout>{children}</Layout></ProtectedRoute>}
export default function App(){return <AuthProvider><BrowserRouter><Routes><Route path="/" element={<Layout><Home/></Layout>}/><Route path="/login" element={<Auth/>}/><Route path="/signup" element={<Auth signup/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/discover" element={<Protected><DiscoverPage/></Protected>}/><Route path="/matches" element={<Protected><ConnectionsPage/></Protected>}/><Route path="/messages" element={<Protected><MessagesPage/></Protected>}/><Route path="/communities" element={<Protected><CommunitiesPage/></Protected>}/><Route path="/profile" element={<Protected><ProfilePage/></Protected>}/><Route path="/profile/:username" element={<Protected><PublicProfilePage/></Protected>}/><Route path="/settings" element={<Protected><SettingsPage/></Protected>}/><Route path="/notifications" element={<Protected><NotificationsPage/></Protected>}/><Route path="*" element={<Page title="Page not found"/>}/></Routes></BrowserRouter></AuthProvider>}